### ISSUE TITLE
Feedback on PCB design

### ISSUE THREAD

**Issue by remy** [Staacks/gbinterceptor#11]
**Describe the bug**

Not a bug, more of an "in the field" use report.

One of the boards I had made I sent to a youtuber (RetroBreak) just as a thing to show off, but the first one didn't work. Couldn't work out why, but when he returned it (I sent him a new one) it turned out the pads had ripped up on the connector.

It's carnage! 

![PXL_20230201_122443956](https://user-images.githubusercontent.com/13700/216043269-dfce4083-1c8e-4231-a9f5-290092a969d3.jpg)

On inspection I can see how it happened. The cart port was not 100% flat - I think there's about 0.2mm tilt. I'm not sure if that was from cart insertion or from not being entirely flat when the port was soldered down (I suspect the later).

I wondered if vias under the cart port pins would be more secure (under the actual cart port rather than below to reduce stress if it's bent) - at the same time just "be more careful" is a simpler/cheaper approach.

Obviously feel free to close this right away, just reporting it for you.

**Comment by Staacks** [comment]
Well, it sounds like something I should warn about in the build guide, but I am not entirely sure yet if I understand correctly how that happened.

I assume that you have soldered the two large pads on the other side and that it is one of the cartridge slots with the two pins that fit into the holes in the PCB? I mean, I currently spent most of my evenings pulling out and re-inserting my flash cartridge to test and fix various games and my version still seems perfectly robust. Not to speak about the absurd contraption of testing a Game Genie with the Interceptor.

Was this in a 3d printed case, so that stress might be added from an edge of case pressing on the cartridge?

**Comment by remy** [comment]
You know what, I now think it actually got crushed during transit when I posted the cart to the guy.

I was sure it was working before I sent it, and now looking at the cart slot side by side with another (working) Interceptor, I can see it's actually bent a little:

![PXL_20230201_175235945](https://user-images.githubusercontent.com/13700/216123727-3f612be8-410e-4ee1-8b36-d014e2fb5c89.jpg)

Hmm. Random bad luck on my part.

So completely ignore me - the fact that you're inadvertently stress testing (to me) definitely means there's no design flaw. 

I guess the warning now is: _do not sit on GB Interceptor - does not work as a chair_!

**Comment by Staacks** [comment]
:laughing:
