### ISSUE TITLE
GB Interceptor displaying mirrored video on GameBoy Pocket

### ISSUE THREAD

**Issue by tylerbartlett** [Staacks/gbinterceptor#5]
GB Interceptor displaying mirrored video on GameBoy Pocket (Model: MGB-001)

I have experienced the same mirroring on Windows 10 desktop and Mac laptop. I did use Discord to test on both OSs. Using firmware v1.0.1. I dont have another gameboy to test with to see if its a pocket specific issue, but will try to scrounge one up.

**Comment by Staacks** [comment]
Are you sure that the image actually comes mirrored from the Interceptor? I just checked and Discord's is showing a mirrored preview. Most video chat software does this, so you see yourself like in an actual mirror, which is more comfortable to most people, but the image seen by others should not be mirrored. (Often video chat software also has a button to change this behavior but I could not find one on the Discord webinterface.)

Could you please confirm if the image is also mirrored to others who see your image on Discord or if it is flipped in other software, too (for example in OBS Studio or VLC (on the Mac, the Win version is still causing trouble)).

BTW: Since you mention a MacBook: If it is working there, could you please tell me the model (especially whether it is one with an Intel CPU or a M1/M2). I am still trying to figure out #1 and need some info about those Macs on which it works. And yes, FaceTime and PhotoBooth mirror the image, too.

**Comment by tylerbartlett** [comment]
Hi Sebastion, I checked on the preview situation and everything you said is right. With a second computer I joined discord and the output is not mirrored there.

As far as the Mac its an Intel CPU, but I'll post over in that issue with more info. 

I consider this issue to be closed with resolution. Thank you!

**Comment by Staacks** [comment]
Perfect, thanks. I will add a note on this to the trouble shooting section and the Game Boy Pocket to the list of working devices
