### ISSUE TITLE
R-Type DX

### ISSUE THREAD

**Issue by Megabusterretro** [Staacks/gbinterceptor#6]
**Type of issue**
**Interceptor reports error / Game looks different from Game Boy screen** / other

**Describe the bug**
-Upon booting, graphical anomalies.
-Interceptor reports error when launching on IPS Modded GBC and IPS Modded SP after pressing start to start the game.

**To Reproduce**

**Screenshots**

**Host software (please complete the following information):**
 - OS: [e.g. Windows, MacOS, Linux, ...] Windows 10
 - Software: [e.g. OBS, VLC, ffmpeg, Zoom, ...] OBS

**Game Boy:**
- Model: [e.g. Game Boy Advance AGB-001]
Q5 IPS GBC
IPS Modded GBA SP (Boxypixel Unhinged)
**Game:**
- Title: [e.g. Tetris] R-Type DX
- Version: [Usually printed on the cartridge, e.g. DMG-ZL-NOE]
DMG-AWHE-USA
**Additional context**
![image](https://user-images.githubusercontent.com/122132860/211123822-8792646b-09d8-493f-9955-7565856209b6.png)
![image](https://user-images.githubusercontent.com/122132860/211123835-b30c15c6-702b-4597-822e-d4d501109e87.png)

**Comment by Staacks** [comment]
Thanks for the detailed report. But isn't this a Game Boy Color game? The Interceptor only supports classical ones.

**Comment by Megabusterretro** [comment]
It is a GBC game, but it it also works on the DMG/Classic one.  There were only a handful of games released like this.  It works just fine on the DMG/Classic GB.  The cart is solid black vs the transparent shell.  This thing performs amazing with the Classic GB though, Great Work!
![image](https://user-images.githubusercontent.com/122132860/211162349-ebbb9155-3df0-4b98-ae1f-9d0429e5b4e5.png)
![IMG_7379](https://user-images.githubusercontent.com/122132860/211162461-f7951118-901c-4343-91df-779ed0d47025.JPEG)

**Comment by Staacks** [comment]
Ah, ok, that makes sense. Those games should work fine when run on a DMG, Pocket or Light, but will not work on anything that supports the color mode. Maybe I could eventually make them also work on the Game Boy Color because I suspect that these games would not run in double speed mode, so it should be feasible to just implement a few features that trip the Interceptor here.

Nevertheless, I close this issue here because at the moment this is simply not supported by the Interceptor. I will also add R-Type DX to the compatibility list (I understood correctly that it works as expected on the DMG?).

**Comment by Megabusterretro** [comment]
Yeah, DMG Works great!
