### ISSUE TITLE
Fortified Zone

### ISSUE THREAD

**Issue by Megabusterretro** [Staacks/gbinterceptor#7]
**Type of issue**
Interceptor reports error / Game looks different from Game Boy screen / other
**Black Screen when starting main gameplay**
**Describe the bug**
**Game starts without issue, able to start the game but once the first gameplay screen appears the Interceptor screen goes black.**  
**To Reproduce**
**1. Start Game**

**Screenshots**

**Host software (please complete the following information):**
 - OS: [e.g. Windows, MacOS, Linux, ...]  **Windows**
 - Software: [e.g. OBS, VLC, ffmpeg, Zoom, ...]  **OBS**

**Game Boy:**
- Model: [e.g. Game Boy Advance AGB-001] **Funnyplaying IPS modded DMG and IPS Modded GBC**

**Game:**
- Title: [e.g. Tetris] **Fortified Zone**
- Version: [Usually printed on the cartridge, e.g. DMG-ZL-NOE]  **DMG-IY-USA**

**Additional context**

![image](https://user-images.githubusercontent.com/122132860/211182007-f7ccfba1-1eaf-4557-810b-8b4609d3389d.png)
![image](https://user-images.githubusercontent.com/122132860/211182053-76bc368d-b6c8-4663-b62c-99cfa21b0a67.png)

**Comment by Staacks** [comment]
Jepp, I can reproduce both problems: The glitch during the title screen effect does not surprise me much. The PPU emulation timing can certainly use some improvement and this looks like a good candidate to work on a few details.

In terms of the black screen I have no idea right now what is happening. I did not expect this and the fact that it remains black even if you restart the game seems like it is not just an emulation problem, but a more basic bug of the Interceptor.

Will hopefully find some time to look into it in a few days.

**Comment by Megabusterretro** [comment]
Sounds good!  I have probably ~200 game boy games that I can test for functionality if you would like.  Would this be the best method of submitting a list of verified working titles?  Just submit a Game Bug issue and just state the list of titles working and a screenshot?

**Comment by Staacks** [comment]
Woah, that would be amazing. Any form you can send me the list works for me.

**Comment by Staacks** [comment]
Found the main issue of the black screen: I had the emulated div register linked to my internal clock counter, which stupidly meant that the clock counter jumps when a game resets the div register. This should be a problem for some other games too, so I directly turned it into a new release.

I don't think that I will look into the glitch of the title animation anytime soon, though. Most mid-frame effects work fine, but in this case I think it is not an issue of the inter-line timing, but the intra-line timing (if these terms are a thing). It looks to me as if the problem is that the scroll register is updated while the Interceptor is not yet finished with each line. Unfortunately, the intra-line timing is very tricky on the Interceptor because a) there are some situations in which it just cannot render fast enough and lags slightly behind (making up for it during hsync) and b) the USB communication on the same core can slightly delay the rendering of a line. So, this is a bigger thing to tackle at some point with a few creative ideas...
